Fatal error: exception Failure("expecting 2 arguments in foo(42)")
